/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$footer_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<div id=\"footer\">\n  <p>\n    &copy; 2011 Jean Yang.\n    Powered by <a href=\"https://sites.google.com/site/jeevesprogramming/\" target=\"blank\">The Jeeves Programming Language</a>.\n  </p>\n</div>" );
    }
  }
}


class $_scalate_$footer_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$footer_ssp.$_scalate_$render(context)
}
