/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$login_screen_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      ;{
        val map: Map[String,String] = $_scalate_$_context.attribute("map")
                 
   val title = map("title")
   var errorMsg = "" 


        $_scalate_$_context << ( "\n" );
        if (map.contains("msg")) {
          $_scalate_$_context << ( "\n   \t\terrorMsg = map(\"msg\") \n" );
        }
        $_scalate_$_context << ( "\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n  <title>" );
        $_scalate_$_context <<< (         title
 );
        $_scalate_$_context << ( "</title>\n  <link href=\"stylesheets/default.css\" rel=\"stylesheet\" type=\"text/css\" />\n  " );
        $_scalate_$_context <<< (         include("snippets/goToLink.ssp")
 );
        $_scalate_$_context << ( "\n</head>\n<body>\n<div id=\"wrapper\">\n  " );
        $_scalate_$_context <<         layout("snippets/header.ssp", Map())
 {
          $_scalate_$_context << ( " " );
        }
        $_scalate_$_context << ( "\n  " );
        $_scalate_$_context <<         layout("snippets/processing.ssp")
 {
          $_scalate_$_context << ( " " );
        }
        $_scalate_$_context << ( "\n  <div id=\"content\">\n    " );
        if (errorMsg != null) {
          $_scalate_$_context << ( "\n      <p><i>" );
          $_scalate_$_context <<< (            errorMsg 
 );
          $_scalate_$_context << ( "</i></p>\n    " );
        }
        $_scalate_$_context << ( "    @form(routes.Application.userInfo) {\n\n      @inputText(userForm(\"userName\"))\n\n      <input type=\"submit\" value=\"Login\">\n\n   }\n    <form action=\"login_user\" method=\"post\">\n    <input type=\"hidden\" name=\"ac\" value=\"log\">\n    <table>\n    <tr>\n      <td><b>E-mail</b></td>\n      <td><input type=\"text\" name=\"username\" size=15 maxlength=50 /></td>\n    </tr>\n    <tr>\n      <td><b>Password</b></td>\n      <td><input type=\"password\" name=\"password\" size=15 maxlength=20 /></td>\n    </tr>\n    </table>\n    <p>\n      <input type=\"submit\" onclick=\"javascript:goToLink('login_user')\" name=\"action\" class=\"button\" value=\"Log In\" />\n      <input type=\"submit\" onclick=\"javascript:goToLink('login_user')\" name=\"action\" class=\"button\" value=\"Sign Up\" />\n      <input type=\"submit\" onclick=\"javascript:goToLink('login_user')\" name=\"action\" class=\"button\" value=\"Send Password\" />\n    </p>\n    </form>\n  </div>\n  " );
        $_scalate_$_context <<< (         include("footer.ssp")
 );
        $_scalate_$_context << ( "\n</div>\n</body>\n</html>" );
      }
    }
  }
}


class $_scalate_$login_screen_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$login_screen_ssp.$_scalate_$render(context)
}
