/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package snippets

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$goToLink_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<script language=\"javascript\" type=\"text/javascript\">\nfunction showDiv() {if (document.getElementById) { // DOM3 = IE5, NS6\ndocument.getElementById('hideShow').style.visibility = 'visible';\n}\nelse {\nif (document.layers) { // Netscape 4\ndocument.hideShow.visibility = 'visible';\n}\nelse { // IE 4\ndocument.all.hideShow.style.visibility = 'visible';\n}\n}\n} function goToLink(lname){\nshowDiv();\nreturn;\n//document.location.href = lname;\n}\n</script>" );
    }
  }
}


class $_scalate_$goToLink_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$goToLink_ssp.$_scalate_$render(context)
}
