/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package snippets

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$header_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      ;{
        val user: cap.jeeves.jconf.backend.ConfUser = $_scalate_$_context.attributeOrElse("user", null)
        $_scalate_$_context << ( "<div id=\"header\">\n  <a href=\"index\"><h1>JConf</h1></a>\n</div>\n<div id=\"menu\">\n  <ul>\n    <li><a href=\"about\" onclick=\"javascript:goToLink('about')\" accesskey=\"1\" title=\"About\">About</a></li>\n    " );
        if (user != null) {
          $_scalate_$_context << ( "\n      <li><a href=\"index\" onclick=\"javascript:goToLink('index')\" accesskey=\"2\" title=\"Home\">Home</a></li>\n      <li><a href=\"profile\" onclick=\"javascript:goToLink('profile')\" accesskey=\"3\" title=\"Profile\">Profile</a></li>\n      <li><a href=\"logout\" onclick=\"javascript:goToLink('logout')\" accesskey=\"4\" title=\"Logout\">Logout</a></li>\n    " );
        }
        $_scalate_$_context << ( "  </ul>\n</div>" );
      }
    }
  }
}


class $_scalate_$header_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$header_ssp.$_scalate_$render(context)
}
