/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package snippets

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$processing_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<div id=\"hideShow\"\n style=\"padding: 90px; background: rgb(220, 220, 220) none repeat scroll 0% 50%; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; visibility: hidden; width: 619px; position: absolute; float: center; align: center;\">\n<h1>Your request is being processed...</h1>\n<p>We appreciate your patience.</p>\n</div>" );
    }
  }
}


class $_scalate_$processing_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$processing_ssp.$_scalate_$render(context)
}
